news/urls.py
from os import name
from django.urls import path

from news.models import Articolo,Giornalista
from .views import *

app_name="news"

urlpatterns = [
    path('', home, name="homeview"),
    #path("articoli/<int:pk>", articoloDetailView, name="articolo_detail")
    path("articoli/<int:pk>", ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path("lista_articoli/",ArticoloListView.as_view(), name="lista_articoli"),
    path("giornalisti/<int:pk>", GiornalistaDetailViewCB.as_view(), name="giornalisti_detail"),
    path("lista_giornalisti/",GiornalistaListView.as_view(), name="lista_giornalisti"),
]

prima_app/urls.py
from os import name
from django.urls import path
from prima_app.views import homepage,welcome,lista,chi_siamo,index
from prima_app.views import variabili

app_name="prima_app"
urlpatterns=[
    path('', index, name='index'),
    path('homepage',homepage,name='homepage'),
    path('welcome',welcome,name='welcome'),
    path('lista', lista ,name='lista'),
    path('chi_siamo',chi_siamo , name="chi_siamo"),
    path('variabili',variabili,name="variabili"),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("prima_app.urls",namespace="prima_app")),
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app")),
    path('news/',include("news.urls",namespace="news")),
    path('prova_pratica_1/',include("prova_pratica_1.urls",namespace="prova_pratica_1")),
]

prova_pratica_1/urls.py
from django.urls.conf import path
from django.urls import path
from prova_pratica_1.views import view_c,view_b

app_name="prova_pratica_1"
urlpatterns=[
    path('view_b',view_b,name="view_b"),
    path('view_c',view_c,name='view_c')
]

seconda_app/urls.py
from os import name
from django.urls import path
from seconda_app.views import es_if,if_else_elif,es_for

app_name="seconda_app"
urlpatterns=[
    path('es_if',es_if,name='es_if'),
    path('if_else_elif',if_else_elif,name='if_else_elif'),
    path('es_for',es_for,name='es_for')
]

news/models.py
from django.db import models
from django.db.models.deletion import CASCADE

class Giornalista(models.Model):
    nome=models.CharField(max_length=20)
    cognome=models.CharField(max_length=20)

    #def __str__(self):
    #    return self.nome+ " "+self.cognome

    class Meta:
        verbose_name="Giornalista"
        verbose_name_plural="Giornalisti"

class Articolo(models.Model):
    titolo=models.CharField(max_length=100)
    contenuto=models.TextField()
    giornalista=models.ForeignKey(Giornalista, on_delete=CASCADE, related_name="articoli")

    #def __str__(self):
    #    return self.titolo

    class Meta:
        verbose_name="Articolo"
        verbose_name_plural="Articoli"

prova_pratica_1/models.py
from django.db import models

# Create your models here.

news/views.py
from django.http import HttpResponse, response
from django.shortcuts import get_object_or_404, render
from .models import Articolo,Giornalista
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

def home(request):
    articoli=Articolo.objects.all()
    giornalisti=Giornalista.objects.all()
    context={"articoli":articoli, "giornalisti":giornalisti}
    print(context)
    return render(request, "homepage.html", context)

def articoloDetailView(request,pk):
    articolo=get_object_or_404(Articolo,pk=pk)
    context={"articolo":articolo}
    return render(request, "articolo_detail.html", context)

class ArticoloDetailViewCB(DetailView):
    model=Articolo
    template_name="articolo_detail.html"

class ArticoloListView(ListView):
    model=Articolo
    template_name="lista_articoli.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["articoli"] = Articolo.objects.all()
        return context


def giornalistaDetailView(request,pk):
    giornalista=get_object_or_404(Articolo,pk=pk)
    context={"giornalista":giornalista}
    return render(request, "giornalista_detail.html", context)

class GiornalistaDetailViewCB(DetailView):
    model=Giornalista
    template_name="giornalista_detail.html"

class GiornalistaListView(ListView):
    model=Giornalista
    template_name="lista_giornalisti.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["giornalista"] = Giornalista.objects.all()
        return context

prima_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,"index.html")
def homepage(request):
    return render(request,"homepage.html")
def welcome(request):
    return render(request,"welcome.html")
def lista(request):
    return render(request,"lista.html")
def chi_siamo(request):
    return render(request,"chi_siamo.html")
def variabili(request):
    context= {
        'var1': 'Prima variabile',
        'var2': 'Seconda variabile',
        'var3': 'Terza variabile',
    }
    return render(request,"variabili.html",context)

prova_pratica_1/views.py
from django.shortcuts import render

def view_b(request):
    materie={
        'm1':"Matematica",
        'm2':"Italiano",
        'm3':"Inglese",
        'm4':"Storia",
        'm5':"Geografia"
    }
    return render(request,"view_b.html",materie)

def view_c(request):
    context={
        'GiuseppeGullo':[("Matematica",9,0),("Italiano",7,3),("Inglese",7.5,4),("Storia",7.5,4),("Geografia",5,7)],
        'AntonioBarbera':[("Matematica",8,1),("Italiano",6,1),("Inglese",9.5,0),("Storia",8,2),("Geografia",8,1)],
        'NicolaSpina':[("Matematica",7.5,2),("Italiano",6,2),("Inglese",4,3),("Storia",8.5,2),("Geografia",8,2)]
        }
    
    return render(request, "view_c.html", context)

seconda_app/views.py
from django.shortcuts import render
import datetime


# Create your views here.

def es_if(request):
    context = {
        'var1':200,
        'var2':200,
        'var3':300,
    }
    return render(request,"es_if.html",context)
def if_else_elif(request):
    context = {
        'var1':100,
        'var2':100.0,
        'var3':100.50,
    }
    return render(request,"if_else_elif.html",context)
def es_for(request):
    context = {
        'list1': [1,datetime.date(2019,7,16), 'Do not give up!'],
        'list2': [1,datetime.date(2019,7,16), 'Do not give up!']
    }
    return render(request, "es_for.html",context)

news/templates/articolo_detail.html
{% extends 'base.html' %}

{% block title %}
    {{articolo.titolo}}
{% endblock title %}

{% block content %}
    <h1>{{articolo.titolo}}</h1>
    <h3>{{articolo.contenuto}}</h3>
    <h5>Autore: {{articolo.giornalista}}</h5>
{% endblock content %}

news/templates/giornalista_detail.html
{% extends 'base.html' %}

{% block title %}
{{articolo.titolo}}
{% endblock title %}

{% block content %}
    <p><strong>Nome: </strong>{{giornalista.nome}}</p>
    <p><strong>Cognome: </strong>{{giornalista.cognome}}</p>
    <hr>
{% endblock content %}

news/templates/homepage.html
{% extends 'base.html' %}
{% block title %}
    Articoli e Giornalisti
{% endblock title %}
{% block content %}
    <h4>Articoli:</h4>
        {% for articolo in articoli %}
            <p><strong>Titolo: </strong>{{articolo.titolo}}</p>
            <p><strong>Titolo: </strong>{{articolo.contenuto}}</p>
            <p><strong>Titolo: </strong>{{articolo.Giornalista}}</p>
            <hr>
        {% endfor %}
    <h4>Giornalisti:</h4>
        {% for giornalista in giornalisti %}
            <p><strong>Nome: </strong>{{giornalista.nome}}</p>
            <p><strong>Cognome: </strong>{{giornalista.cognome}}</p>
            <hr>
        {% endfor %}
{% endblock content %}

news/templates/lista_articoli.html
{% extends 'base.html' %}
{% block title %}
    Lista Articoli
{% endblock title %}
{% block content %}
    <h4>Articoli:</h4>
        {% for articolo in articoli %}
            <p><strong>Titolo: </strong>{{articolo.titolo}}</p>
            <p><strong>Contenuto: </strong>{{articolo.contenuto}}</p>
            <p><strong>Giornalista: </strong>{{articolo.giornalista}}</p>
            <hr>
        {% endfor %}
{% endblock content %}

news/templates/lista_giornalisti.html
{% extends 'base.html' %}

{% block title %}
    Lista Giornalisti
{% endblock title %}

{% block content %}
    <h4>Giornalisti:</h4>
    {% for giornalista in giornalisti %}
        <p><strong>Nome: </strong>{{giornalista.nome}}</p>
        <p><strong>Cognome: </strong>{{giornalista.cognome}}</p>
        <hr>
    {% endfor %}
{% endblock content %}

prima_app/templates/chi_siamo.html
{% extends "base.html" %}

{% block title %} {{block.super}} {% endblock title %} 

{% block content %}
    <h1>Chi siamo</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus sit dolores molestiae hic optio ipsam quam aliquam sequi atque esse quis debitis possimus, illo accusantium cum, eligendi, nihil perferendis nam.</p>
{% endblock content %}

prima_app/templates/homepage.html
{% extends "base.html" %}

{% block title %} {{ block.super}} {% endblock title %}

{% block content %}
    <h1>Benvenuto</h1>
{% endblock content %}

prima_app/templates/index.html
{% extends "base.html" %}

{% block title %}{{ block.super}}{% endblock title %}

{% block content %}
<ol>
    <li><a href="{% url 'prima_app:homepage' %}">Homepage</a></li>
    <li><a href="{% url 'prima_app:welcome' %}">Welcome</a></li>
    <li><a href="{% url 'prima_app:lista' %}">Lista</a></li>
    <li><a href="{% url 'prima_app:chi_siamo' %}">Chi siamo</a></li>
    <li><a href="{% url 'prima_app:variabili' %}">Variabili</a></li>
    <li><a href="{% url 'seconda_app:es_for' %}">For</a></li>
    <li><a href="{% url 'seconda_app:es_if' %}">If</a></li>
    <li><a href="{% url 'seconda_app:if_else_elif' %}">Elif</a></li>
</ol>
{% endblock content %}

prima_app/templates/lista.html
{% extends "base.html" %}

{% block title %} {{block.super}} {% endblock title %}

{% block content %}
    <h1>Lista</h1>
    <ol>
        <li>Primo</li>
        <li>Secondo</li>
        <li>Terzo</li>
    </ol>
{% endblock content %}

prima_app/templates/variabili.html
{% extends "base.html" %}

{% block title %} {{block.super}} {% endblock title %}
    
{% block content %}
    <ol>
        <li>{{var1}}</li>
        <li>{{var2}}</li>
        <li>{{var3}}</li>
    </ol>
{% endblock content %}

prima_app/templates/welcome.html
{% extends "base.html" %}

{% block title %} {{block.super}} {% endblock title %}

{% block content %}
    <h1>Welcome</h1>
    <p>Welcome in inglese vuol dire italiano</p>
{% endblock content %}

prova_pratica_1/templates/view_b.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}

    {% block content %}
    <h2>Materie:</h2>
        <ul>
            <li>{{m1}}</li>
            <li>{{m2}}</li>
            <li>{{m3}}</li>
            <li>{{m4}}</li>
            <li>{{m5}}</li>
        </ul>
    {% endblock %}
</body>
</html>

prova_pratica_1/templates/view_c.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}

    {% block content %}
        <ul>
            <h3>Giuseppe Gullo:</h3>
            {% for x in GiuseppeGullo %}
                <li>{{x}}</li>
            {% endfor %}
            <h3>Antonio Barbera:</h3>
            {% for x in AntonioBarbera %}
                <li>{{x}}</li>
            {% endfor %}
            <h3>Nicola Spina:</h3>
            {% for x in NicolaSpina %}
                <li>{{x}}</li>
            {% endfor %}
        </ul>
    {% endblock %}
</body>
</html>

seconda_app/templates/es_for.html
{% extends "base.html" %}

{% block title %} {{ block.super}} {% endblock title %}

{% block content %}
    Cicla una sequenza usando <b>forloop.counter</b>
    <br/>
    {% for x in list2 %}
        <i>{{ forloop.counter}}</i> : {{ x }}</br>
    {% endfor %}
    <br/>
    Cicla una sequenza usando <b>forloop.counter0</b>
    <br/>
    {% for x in list2 %}
        <i>{{ forloop.counter0}}</i> : {{ x }}</br>
    {% endfor %}
    <br/>
    Stampa il primo elemento della sequenza usando <b>forloop.first</b>:
    <br/>
    {% for x in list2 %}
        {% if forloop.first %}
            <i>Il primo elemento</i> - {{ x }}
        {% endif %}
    {% endfor %}
    <br/>
    Stampa l'ultimo elemento della sequenza usando <b>forloop.last</b>:
    <br/>
    {% for x in list2 %}
        {% if forloop.last %}
            <i>L'ultimo elemento</i> - {{ x }}
        {% endif %}
    {% endfor %}
    <br/>
    Stampa il numero degli elementi non ancora ciclati usando <b>forloop.revcounter</b>:
    <br/>
    {% for x in list2 %}
        <i>numero degli elementi da dover ancora ciclare</i> - {{ forloop.revcounter }}<br/>
        <i>Elemento</i> - {{ x }}<br/>
    {% endfor %}
    <br/>
    Stampa il numero degli elementi non ancora ciclati usando <b>forloop.revcounter0</b>:
    <br/>
    {% for x in list2 %}
        <i>numero degli elementi da dover ancora ciclare</i> - {{ forloop.revcounter0 }}<br/>
        <i>Elemento</i> - {{ x }}<br/>
    {% endfor %}
    <br/>
    Stampa la sequenza al contrario usando <b>forloop.revcounter</b>:
    <br/>
    {% for x in list2 %}
        <i>Elemento</i> - {{ x }}<br/>
    {% endfor %}
    <br/>
{% endblock content %}

seconda_app/templates/es_if.html
{% extends "base.html" %}

{% block title %} {{block.super}} {% endblock title %}

{% block content %}
    <b>var1 = {{ var1 }}</b> <br>
    <b>var2 = {{ var2 }}</b> <br>
    <b>var3 = {{ var3 }}</b> <br>
    {% if var1 < var2 %}
        <p><i>var1 è minore di var2</i></p>
    {% endif %}
    {% if var1 > var2 %}
        <p><i>var1 è maggiore di var2</i></p>
    {% endif %}
    {% if var1 <= var2 %}
        <p><i>var1 è minore o uguale di var2</i></p>
    {% endif %}
    {% if var1 >= var2 %}
        <p><i>var1 è maggiore o uguale di var2</i></p>
    {% endif %}
    {% if var1 == var2 %}
        <p><i>var1 è uguale a var2</i></p>
    {% endif %}
    {% if var1 != var2 %}
        <p><i>var1 non è uguale a var2</i></p>
    {% endif %}
    {% if var1 < var2 and var1 < var3 %}
        <p><i>var1 è minore di var2 e di var3</i></p>
    {% endif %}
    {% if var1 < var2 or var3 < var2 %}
        <p><i>var1 è minore di var2 o var3 è minore di var2</i></p>
    {% endif %}
    {% if not var1 > var2 %}
        <p><i>var1 non è maggiore di var2</i></p>
    {% endif %}
{% endblock content %}

seconda_app/templates/if_else_elif.html
{% extends "base.html" %}

{% block title %} {{block.super}} {% endblock title %}

{% block content %}
    <b>var1 = {{ var1 }}</b> <br>
    <b>var2 = {{ var2 }}</b> <br>
    <b>var3 = {{ var3 }}</b> <br>
    {% if var1 < var2 %}
        <p><i>var1 è minore di var2</i></p>
    {% elif var1 > var2 %}
        <p><i>var1 è maggiore di var2</i></p>
    {% else %}
        <p><i>var1 è uguale a var2</i></p>
    {% endif %}
    {% if var1 > var2 %}
        <p><i>var1 è maggiore di var2</i></p>
    {% elif var1 < var2 %}
        <p><i>var1 è minore di var2</i></p>
    {% else %}
        <p><i>var1 è uguale a var2</i></p>
    {% endif %}
    {% if var1 <= var2 %}
        <p><i>var1 è minore o uguale di var2</i></p>
    {% elif var1 > var2 %}
        <p><i>var1 è maggiore di var2</i></p>
    {% endif %}
    {% if var1 >= var2 %}
        <p><i>var1 è maggiore o uguale di var2</i></p>
    {% elif var1 < var2 %}
        <p><i>var1 è minore di var2</i></p>
    {% endif %}
    {% if var1 == var2 %}
        <p><i>var1 è uguale di var2</i></p>
    {% elif var1 != var2 %}
        <p><i>var1 non è uguale di var2</i></p>
    {% endif %}
    {% if var1 < var2 and var1 < var3 %}
        <p><i>var1 è minore di var2 e var3</i></p>
    {% elif var1 > var2 and var1 > var3 %}
        <p><i>var1 è maggiore di var2 e var3</i></p>
    {% endif %}
    {% if var1 > var2 %}
        <p><i>var1 non è maggiore di var2</i></p>
    {% elif var1 < var2 %}
        <p><i>var1 non è minore di var2</i></p>
    {% else %}
        <p><i>var1 è uguale a var2</i></p>
    {% endif %}
{% endblock content %}

templates/base.html
<!doctype html> 
{% load static %}
<html lang="it">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}Base{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
</head>

<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'prima_app:index'%}">Home <span class="sr-only">(current)</span></a>
      </li>
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Prima App
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <a class="dropdown-item" href="{%url 'prima_app:homepage'%}">Homepage</a>
            <a class="dropdown-item" href="{%url 'prima_app:welcome'%}">Welcome</a>
            <a class="dropdown-item" href="{%url 'prima_app:lista'%}">Lista</a>
            <a class="dropdown-item" href="{%url 'prima_app:chi_siamo'%}">Chi Siamo</a>
            <a class="dropdown-item" href="{%url 'prima_app:variabili'%}">Variabili</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Seconda App
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <a class="dropdown-item" href="{%url 'seconda_app:es_for'%}">For</a>
                    <a class="dropdown-item" href="{%url 'seconda_app:es_if'%}">If</a>
                    <a class="dropdown-item" href="{%url 'seconda_app:if_else_elif'%}">Elif</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          News
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <a class="dropdown-item" href="{%url 'seconda_app:es_for'%}"></a>
                    <a class="dropdown-item" href="{%url 'news:lista_articoli'%}">Articoli</a>
                    <a class="dropdown-item" href="{%url 'news:lista_giornalisti'%}">Giornalisti</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Prova pratica 1
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <a class="dropdown-item" href="{%url 'seconda_app:es_for'%}"></a> 
                    <a class="dropdown-item" href="{%url 'prova_pratica_1:view_b'%}">view_b</a>
                    <a class="dropdown-item" href="{%url 'prova_pratica_1:view_c'%}">view_c</a>
        </div>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

   

    <div class="container my-4">
        {%block content%} {%endblock content%}
    </div>
</body>

</html>